name: Testing stuff

on:
  push:
    branches:
      - view-commit-messages

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: join commit messages
        env:
          COMMIT_MESSAGES_J: ${{ join(env.COMMIT_MESSAGES) }}
        run: echo "$COMMIT_MESSAGES_J"
      - name: check for skip
        env:
          SKIP_V: ${{ contains(env.COMMIT_MESSAGES_J,'#skip') }}
        run: echo "$SKIP_V"
